### ISSUE TITLE
sensortype_args.csv not working with comment lines

### ISSUE THREAD

**Issue by janbeutel** [janbeutel/GSN#3]
lines like this used to structure the sensortype-args file do not work (error on parsing)

# nodehealth

**Comment by manuelbcr** [comment]
this should be related to the issue from the email. 

```
if (logger.isDebugEnabled()) {
   try {
      String[] args = { "-webPort", "8082", "-webAllowOthers", "false" };
      web = Server.createWebServer(args);
      web.start();
   } catch (SQLException e) {
      logger.warn(e.getMessage(), e);
   }
}
```
in DataMappingWrapper.java line 154 caused the mappings not being successfully initialized because there is an error with the args in case the log4j.conf is set to log level=debug. The issue here is that the flag -webAllowOthers had to be specified with false in an older version of the library. With the change to a newer version the flag just needs to be set in case you want it to be true. For now it should work if the log level in the log4j.conf is set to info but we will fix this tomorrow along with issue #2
